apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-bot
  namespace: revcog

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: jenkins-bot
    namespace: revcog
